version: '3.1'
services:
  app:
    container_name: university-postgresql
    image: university-postgresql
    build: ./
    ports:
       - "8080:8080"
    depends_on:
       - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=University